### PR TITLE
Master

### PR DESCRIPTION
**Pull request by StarPupil**

### CODE REVIEW

**Comment by jcarolus** [comment]
Thanks! Will look into it and merge later.

**Comment by StarPupil** [comment]
Oh shoot. Look, I'm sorry, a group for one of my classes is using your
project as a starting point for a project, and I think I may have
accidentally pushed to the main branch. Disregard anything that I did, as
it was probably just adding in JUnit stuff, and you seem to have a pretty
good idea what you're doing, and it would probably screw something up. So
just ignore it. Sorry to make trouble.

**Comment by jcarolus** [comment]
Well, it can be valuable to have students fork the project and actually make pull-requests, so they get experience in online collaboration. It's an extra motivation to have a feature that you develop appearing in an app on the Play store too :+1: 

The code needs a lot of improvements, refactoring unit testing etc... so plenty of opportunities!

**Comment by StarPupil** [comment]
Well, we'll try to do something cool. Out of curiosity, what features do
you think would be good to add? It seems like a pretty well fleshed out
project. I know the computer beat the pants off of me.

**Comment by jcarolus** [comment]
It beats me too...
There is the issues section on the repository
https://github.com/jcarolus/android-chess/issues
in which I would encourage to add new items too.

But mainly, to learn to code, I think there is a lot to refactor. I have been throwing code a lot, and not spend a lot of time designing and refactoring. Improving bad code is a good way to learn to code!

**Pull request closed without merging**
